// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWXsOvHpGBk_QhKz6T8DUSmw7z4gTiyI8',
    appId: '1:503923325128:web:4aefd75695b4e3caaa4dfd',
    messagingSenderId: '503923325128',
    projectId: 'navalha-prod',
    authDomain: 'navalha-prod.firebaseapp.com',
    storageBucket: 'navalha-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7a9ocze1zdggtXRl1CuYWmftxGlj7jfI',
    appId: '1:503923325128:android:eb74c8fe884fd968aa4dfd',
    messagingSenderId: '503923325128',
    projectId: 'navalha-prod',
    storageBucket: 'navalha-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnePJJ81LqQUlq4aJwHypdwywvBulELAA',
    appId: '1:503923325128:ios:3eaa2fc8860e768baa4dfd',
    messagingSenderId: '503923325128',
    projectId: 'navalha-prod',
    storageBucket: 'navalha-prod.appspot.com',
    androidClientId:
        '503923325128-0jid4lrlq2nkvhanrslo6s4t5m9cqsb7.apps.googleusercontent.com',
    iosClientId:
        '503923325128-77lrcenmifh5hj1ak32lrhis2g6ouebm.apps.googleusercontent.com',
    iosBundleId: 'customer.navalha',
  );
}
